spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0


rocketmq:
  name-server: localhost:9876
  producer:
    group: my-group



mybatis-plus:
  mapper-locations:
    - classpath*:com/codeman/**/xml/*Mapper.xml
    - classpath:mapper/*.xml
    - classpath:dao/*.xml


