spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_mall?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  elasticsearch:
    rest:
      uris: localhost:9200

mybatis-plus:
  mapper-locations:
    - classpath*:com/codeman/**/xml/*Mapper.xml
    - classpath:mapper/*.xml
    - classpath:dao/*.xml